# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: EOC Snapshot Build

on:
  push:
    branches: 
      - 'main'
  pull_request:
    branches: 
      - 'main'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone EOC repository
      uses: actions/checkout@v2
      with:
        path: EOC-1.12

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - uses: burrunan/gradle-cache-action@v1

    - name: Cache .gradle
      with:
        job-id: eoc

    - name: Grant execute permission for gradlew
      run: chmod +x ./EOC-1.12/gradlew

    - name: CI Setup
      run: cd ./EOC-1.12/ && ./gradlew setupCIWorkspace

    - name: Build
      run: cd ./EOC-1.12/ && ./gradlew build

    - uses: actions/upload-artifact@v2
      with:
        name: EOC snapshot
        path: ./EOC-1.12/build/libs

    - name: Create a new GitHub release if a new tag is pushed
      uses: softprops/action-gh-release@v0.1.5
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      with:
        prerelease: true
        files: |
          ./EOC-1.12/build/libs/*
        body: |
          ## 更新日志
          * 这是 GitHub Action 自动化部署，更新日志将会手动更新。
